const { Router } = require('express');
const ctrl = require('../controllers/studentController');
const { validateStudent, validateStudentPatch } = require('../middleware/validate');
const { optionalAuth, requireAuth } = require('../middleware/auth');
const r = Router();
r.get('/', optionalAuth, ctrl.list);
r.post('/', requireAuth, validateStudent, ctrl.create);
r.patch('/:id', requireAuth, validateStudentPatch, ctrl.update);
r.delete('/:id', requireAuth, ctrl.remove);
module.exports = r;
